### ISSUE TITLE
Please make this plugin available for Linux. 

### ISSUE THREAD

**Issue by amoore2600** [ratwithacompiler/OBS-captions-plugin#18] opened 2020-04-12 20:49 UTC
Please make this plugin available for Linux. 

I am available to test via Linux if needed.

**Comment by aral** [comment] 2020-06-30 15:37
+1 :)

**Comment by ratwithacompiler** [comment] 2020-07-18 08:19
Duplicate of https://github.com/ratwithacompiler/OBS-captions-plugin/issues/5 
Linux beta build out now.

**Closed by ratwithacompiler** 2020-07-18 08:19 UTC
