### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by kajtielplu** [ratwithacompiler/OBS-captions-plugin#39] opened 2020-08-14 20:45 UTC
Hello. I'm having an issue where the CPU usage increases constantly when captions are enabled. It starts out okay but has gotten as high as 95% before I shut off the stream. The CPU usage doesn't go down again until I close OBS. I'm running Ubuntu 20.04.
My system info (just in case it's relevant):

> CPU: Quad Core AMD Ryzen 5 3400G with Radeon Vega Graphics (-MT MCP-) 
Speed: 1923 MHz Kernel: 5.4.0-42-generic x86_64 Up: 12h 05m 
Mem: 4721.1/14004.7 MiB (33.7%) Storage: 2.73 TiB (36.6% used) Procs: 312 
Shell: bash 5.0.17 inxi: 3.0.38 

[log with captions on.txt](https://github.com/ratwithacompiler/OBS-captions-plugin/files/5077086/log.with.captions.on.txt)
[log with captions off.txt](https://github.com/ratwithacompiler/OBS-captions-plugin/files/5077109/log.with.captions.off.txt)
![Screenshot showing the difference in CPU usage in System Monitor](https://user-images.githubusercontent.com/69696660/90290257-deb96300-dec0-11ea-9dd6-d00d9813accd.png)

**Comment by kajtielplu** [comment] 2020-08-19 05:39
Hello again. I tried the latest release of the plugin, and it works great for about ten minutes, before the CPU usage goes wild and maxes out after about 50 minutes.
(The time on this CPU history graph is set to a different scale to the previous one.)
![Screenshot from 2020-08-19 15-32-05](https://user-images.githubusercontent.com/69696660/90596165-b5d2fe00-e231-11ea-8e2b-f6a19b42417e.png)

**Comment by ratwithacompiler** [comment] 2020-08-19 07:19
Hi. The linux version isn't used by particularly many people and not really tested well unfortunately, sorry.

I tested in Ubuntu 20.04 VM now for about an hour with local recording transcripts enabled but couldn't reproduce the issue, CPU usage was constant 45%ish for me. The log file also doesn't show anything that sticks out to me, so quite honestly I don't really have any idea what's going wrong there right now.

**Comment by kajtielplu** [comment] 2020-08-19 09:50
Thanks for looking into it. I ran another test with verbose logging; it'd be great if you could have a look at it. The increase in CPU usage seems to depend on how much dialogue is being transcribed, not just increasing because the plugin is turned on.
[obsverboselog.txt](https://github.com/ratwithacompiler/OBS-captions-plugin/files/5095500/obsverboselog.txt)
I don't mind doing more testing if necessary. I think this is a really cool project.

**Comment by MigrantP** [comment] 2020-08-23 20:38
Just did a stream with the new release and captions on, and everything is now copacetic on Mac. Thanks!

**Comment by schnettgoecke** [comment] 2020-08-23 20:41
Just wanted to add another positive anecdote: I streamed for 5 hours straight on a 2013 MacBook Pro and it was solid! No CPU issues at all with the newest version. Thanks!

**Comment by ratwithacompiler** [comment] 2020-08-25 00:01
Closing since fixed now. Thanks for the detailed logs @kajtielplu @marcmagus and testing everyone!

**Closed by ratwithacompiler** 2020-08-25 00:01 UTC
Labels: bug
